import './globals.css'
import { Akshar } from 'next/font/google'

const akshar = Akshar({ subsets: ['latin'] })

export const metadata = {
  title: 'AlEd',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={akshar.className}>{children}</body>
    </html>
  )
}
